version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.dev
    container_name: nextjs_app
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace
      - /workspace/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
    depends_on:
      - pocketbase
    networks:
      - devnet

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase_service
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb_data
    networks:
      - devnet
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  devnet:
    driver: bridge

volumes:
  pocketbase_data: