import type { Metadata } from "next";
import "@/styles/globals.css";
import { languages } from "@/lib/i18n/settings";
import { LayoutProps } from "@/types/layoutProps";
import { ThemeProvider } from "next-themes";
import { cn } from "@/lib/utils";
import { darker_grotesque } from "@/lib/font";

export const metadata: Metadata = {
  title: "OCamp App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

const RootLayout = ({ children, params }: LayoutProps) => {
  return (
    <html lang={params.lng} suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={cn(
          `min-h-screen bg-white text-zinc-800 overflow-y-hidden dark:bg-zinc-800 dark:text-white ${darker_grotesque.className} antialiased overflow-y-hidden`,
          darker_grotesque.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
